version: "3.7"
services:
  bpms_app:
    image: jboss/jbpm-server-full
    container_name: bpms
    restart: always
    environment:
      - JBPM_DB_DRIVER=postgres
      - JBPM_DB_HOST=bpms_db
      - JBPM_DB_PORT=5432
      - JBPM_DB_NAME=bpms
      - JBPM_DB_USER=bpms
      - JBPM_DB_PASSWORD=bpms
    volumes:
      - ./bpms_activos:/opt/jboss/wildfly/bin/.niogit:Z
    depends_on:
      - bpms_db
    ports:
      - 8080:8080
      - 8001:8001
    networks:
      - bpms-network

  bpms_db:
    image: postgres
    container_name: bpms-db
    restart: always
    environment:
      - POSTGRES_DB=bpms
      - POSTGRES_USER=bpms
      - POSTGRES_PASSWORD=bpms
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bpms-network

volumes:
  database: {}
  bpms_activos: {}

networks:
  bpms-network:
    external: true